meta_title: "Pronostik - Bet on the future, outsmart experts and stay ahead of the curve."
meta_description: "Pronostik lets you bet on various questions and have access to interesting statistics on current events. Together, we can stay ahead of the curve."
meta_image: "logoProno.png"  # A picture in your app / assets / images /
twitter_account: "@nomdevotrecompte"  # essential for Twitter Cards
